# Generated by Django 5.1.4 on 2024-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nis', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
    ]
